Repository gip-inclusion/le-marche, pull requests merged in 2023-02, with the labels that each got.

#630 Ajouter une question sur le montant des dépôts de besoins
  lemarche/templates/tenders/create_step_description.html
  lemarche/tenders/admin.py
  lemarche/tenders/constants.py
  lemarche/tenders/migrations/0042_tender_why_amount_is_blank.py
  lemarche/tenders/models.py
  lemarche/www/tenders/forms.py
Labels: recette-jetable

#635 Partage de la liste de recherche - 1
  lemarche/static/vendor/alpinejs@3.11.1.min.js
  lemarche/templates/layouts/base.html
  lemarche/templates/siaes/_download_click_survey_modal.html
  lemarche/templates/siaes/_download_click_survey_modal_content.html
  lemarche/templates/siaes/_share_click_survey_modal_download_content.html
  lemarche/templates/siaes/_share_search_results.html
  lemarche/templates/siaes/search_results.html
  lemarche/www/siaes/forms.py
  lemarche/www/siaes/views.py
Labels: recette-jetable

#641 Ajout de filtres complexe pour le dépôt de besoins dans l'admin
  config/settings/base.py
  config/urls.py
  lemarche/cms/migrations/0001_initial.py
  lemarche/cms/models.py
  lemarche/cms/snippets.py
  lemarche/static/itou_marche/admin.css
  lemarche/templates/admin/base.html
  lemarche/tenders/admin.py
  poetry.lock
  pyproject.toml
  requirements/dev.txt
  requirements/staging.txt
Labels: recette-jetable

#646 Réseau : pouvoir filtrer par périmètre (région)
  lemarche/perimeters/models.py
  lemarche/templates/dashboard/profile_network_siae_list.html
  lemarche/www/dashboard/urls.py
  lemarche/www/dashboard/views.py
  lemarche/www/siaes/forms.py
Labels: recette-jetable

#653 Calcul d'impact à la création d'un besoin
  lemarche/templates/tenders/create_step_description.html
  lemarche/www/tenders/forms.py
Labels: recette-jetable

#670 Fix du bug du montant obligatoire à la création du dépôt de besoin
  lemarche/www/tenders/forms.py
Labels: recette-jetable

#669 Simplification du partage de liste de structures
  lemarche/static/js/utils.js
  lemarche/templates/siaes/_share_click_survey_modal_download_content.html
  lemarche/templates/siaes/_share_search_results.html
  lemarche/templates/siaes/search_results.html
  lemarche/utils/urls.py
  lemarche/www/siaes/views.py
Labels: recette-jetable

#671 Ajout d'un bouton pour inciter les utilisateurs à déposer un besoin dans la liste de favoris
  lemarche/templates/dashboard/profile_favorite_list_detail.html
Labels: enhancement

#679 Fix du bug du calcul de l'impact social à la création de dépôt de besoin
  lemarche/templates/tenders/create_step_description.html
Labels: bug
