Repository gip-inclusion/le-marche, pull requests merged in 2024-12, with the labels that each got.

#1575 feat(Admin): Ajout de 'contact_phone' dans la recherche
  lemarche/tenders/admin.py
Labels: recette-jetable

#1612 fix: Remove dependabot auto pr action
  .github/dependabot.yml
Labels: github_actions

#1615 fix: Autoriser seulement les "GET" sur PerimeterAutocompleteViewSet
  lemarche/api/perimeters/views.py
Labels: bug

#1616 fix: Condition invalide pour échapper le CSRF
  lemarche/www/pages/views.py
Labels: bug

#1620 feat: Inbound email whitelist brevo ips
  config/settings/base.py
  lemarche/api/emails/tests.py
  lemarche/api/emails/views.py
Labels: enhancement

#1619 fix: Erreurs de serialisation des inbound email
  lemarche/api/emails/serializers.py
Labels: bug

#1618 feat: Conversations: anonymize data
  clevercloud/conversations_anonymize_outdated.sh
  clevercloud/cron.json
  config/settings/base.py
  lemarche/conversations/constants.py
  lemarche/conversations/management/commands/anonymize_outdated_conversations.py
  lemarche/conversations/management/commands/delete_outdated_conversations.py
  lemarche/conversations/migrations/0018_conversation_is_anonymized.py
  lemarche/conversations/models.py
  lemarche/conversations/tests.py
Labels: enhancement
