Repository gip-inclusion/le-marche, pull requests merged in 2024-02, with the labels that each got.

#1054 [CMS] Ajout de pages "privée" de wagtails
  config/settings/base.py
  lemarche/cms/migrations/0009_paidarticlelist.py
  lemarche/cms/models.py
  lemarche/templates/cms/paid_article_list.html
  lemarche/users/admin.py
Labels: recette-jetable

#1073 Ouverture de la recherche par mot clé
  lemarche/api/perimeters/tests.py
  lemarche/api/perimeters/views.py
  lemarche/perimeters/models.py
  lemarche/siaes/models.py
  lemarche/static/js/perimeter_autocomplete_field.js
  lemarche/templates/siaes/search_results.html
  lemarche/templates/siaes/semantic_search_results.html
  lemarche/tenders/models.py
  lemarche/utils/apis/api_elasticsearch.py
  lemarche/www/siaes/forms.py
  lemarche/www/siaes/tests.py
  lemarche/www/siaes/views.py
Labels: recette-jetable

#1074 feat(api) Pouvoir chercher les structures par SIREN
  lemarche/api/siaes/tests.py
  lemarche/api/siaes/views.py
  lemarche/api/urls.py
Labels: API

#1075 api(siae): ajoute le parent dans l'endpoint siae kinds
  lemarche/api/siaes/tests.py
  lemarche/api/siaes/views.py
  lemarche/api/utils.py
Labels: API

#1068 [Affichage des Siaes] Ajout du badge visuel des super esi
  lemarche/static/itou_marche/sections/_siae.scss
  lemarche/static/js/utils.js
  lemarche/templates/dashboard/_siae_tab_content.html
  lemarche/templates/dashboard/home_siae.html
  lemarche/templates/siaes/_card_detail.html
  lemarche/templates/siaes/_card_search_result.html
  lemarche/templates/siaes/_card_tender.html
Labels: recette-jetable

#1079 Refonte ergonomique de la liste des opportunités
  lemarche/static/itou_marche/base/_custom.scss
  lemarche/static/itou_marche/base/_variables.scss
  lemarche/static/itou_marche/itou_marche.scss
  lemarche/static/itou_marche/sections/_tender.scss
  lemarche/templates/tenders/_detail_card.html
  lemarche/templates/tenders/_list_item_detail_row.html
  lemarche/templates/tenders/_list_item_siae.html
  lemarche/www/tenders/tests.py
Labels: recette-jetable

#1089 feat(tender): Admin : réduire la taille de la page grâce aux collapse
  lemarche/tenders/admin.py
  lemarche/tenders/models.py
Labels: Admin

#1090 feat(Admin): Ajout d'un filtre pour retrouver les dépôts de besoins incrémentaux
  lemarche/tenders/admin.py
  lemarche/tenders/constants.py
  lemarche/tenders/models.py
  lemarche/tenders/tests.py
Labels: Admin

#1094 refactor: retrait de l'envoi de mail à j+2 aux auteurs de besoins incrémentaux
  clevercloud/cron.json
  clevercloud/tenders_send_author_incremental.sh
  config/settings/base.py
  lemarche/tenders/management/commands/send_author_incremental_emails.py
  lemarche/www/tenders/tasks.py
Labels: recette-jetable

#1101 refactor(tender): Admin : ré-ajoute les stats du nombre de structures qui ont vues et qui ont cliquées
  lemarche/tenders/admin.py
Labels: recette-jetable

#1085 feat(besoins): Sondage aux prestataires intéressés : cron & task
  clevercloud/cron.json
  clevercloud/tenders_send_siae_transactioned_question_emails.sh
  config/settings/base.py
  lemarche/tenders/management/commands/send_author_transactioned_question_emails.py
  lemarche/tenders/management/commands/send_siae_transactioned_question_emails.py
  lemarche/www/tenders/tasks.py
Labels: Dépôt de besoin, Emails
