Repository gip-inclusion/le-marche, pull requests merged in 2025-02, with the labels that each got.

#1635 fix: value error recherche prestataire => passage django 4.2 => 5.1
  .pre-commit-config.yaml
  config/settings/base.py
  config/settings/test.py
  lemarche/companies/factories.py
  lemarche/conversations/tests.py
  lemarche/cpv/factories.py
  lemarche/crm/tests.py
  lemarche/favorites/factories.py
  lemarche/labels/factories.py
  lemarche/networks/factories.py
  lemarche/sectors/factories.py
  lemarche/siaes/admin.py
  lemarche/siaes/factories.py
  lemarche/siaes/management/commands/import_esat_from_csv.py
  lemarche/tenders/factories.py
  lemarche/users/factories.py
  lemarche/users/tests.py
  lemarche/utils/fields.py
  lemarche/utils/templatetags/siae_sectors_display.py
  lemarche/www/conversations/tasks.py
  lemarche/www/siaes/views.py
  lemarche/www/tenders/forms.py
  lemarche/www/tenders/tests.py
  poetry.lock
  pyproject.toml
  requirements/dev.txt
  requirements/staging.txt
Labels: bug

#1657 fix: Copie de django-fieldsets-with-inlines
  config/settings/base.py
  lemarche/favorites/admin.py
  lemarche/siaes/admin.py
  lemarche/templates/admin/change_form.html
  lemarche/tenders/admin.py
  lemarche/users/admin.py
  lemarche/utils/admin/inline_fieldset.py
  poetry.lock
  pyproject.toml
  requirements/dev.txt
  requirements/staging.txt
Labels: bug

#1638 fix: bug sur les gestionnaires sur Admin
  lemarche/siaes/admin.py
  lemarche/siaes/migrations/0022_siae_users_m2m_add_through.py
  lemarche/siaes/migrations/0081_fix_improper_migration.py
  lemarche/siaes/migrations/0082_siaeuser_unique_siae_user_for_siaeuser.py
  lemarche/siaes/models.py
  lemarche/users/admin.py
Labels: bug

#1632 feat: Supprimer mailjet
  config/settings/base.py
  env.docker_default.local
  lemarche/api/tenders/tests.py
  lemarche/api/tenders/views.py
  lemarche/conversations/admin.py
  lemarche/conversations/constants.py
  lemarche/conversations/migrations/0020_remove_templatetransactional_mailjet_id_and_more.py
  lemarche/conversations/models.py
  lemarche/conversations/tests.py
  lemarche/siaes/management/commands/sync_with_emplois_inclusion.py
  lemarche/users/tests.py
  lemarche/utils/apis/api_mailjet.py
  lemarche/utils/emails.py
  lemarche/www/auth/views.py
  lemarche/www/pages/views.py
  lemarche/www/siaes/views.py
  lemarche/www/tenders/tasks.py
  lemarche/www/tenders/tests.py
  lemarche/www/tenders/views.py
Labels: enhancement

#1636 fix: wrong GET ids
  lemarche/www/tenders/tests.py
  lemarche/www/tenders/views.py
Labels: bug

#1640 feat: factorisation d'un copié-collé
  lemarche/siaes/management/base_update_api.py
  lemarche/siaes/management/commands/update_api_qpv_fields.py
  lemarche/siaes/management/commands/update_api_zrr_fields.py
Labels: enhancement

#1660 fix: multiple select widget not displaying correctly
  lemarche/templates/auth/signup.html
  lemarche/www/auth/forms.py
Labels: bug

#1641 feat: Enlever les vieux secteurs d'activités liés à une stucture
  lemarche/api/siaes/filters.py
  lemarche/api/siaes/serializers.py
  lemarche/api/siaes/tests.py
  lemarche/api/siaes/views.py
  lemarche/fixtures/django/01_siaes.json
  lemarche/fixtures/django/06_siae_sectors.json
  lemarche/fixtures/tests.py
  lemarche/sectors/factories.py
  lemarche/sectors/models.py
  lemarche/sectors/tests.py
  lemarche/siaes/admin.py
  lemarche/siaes/constants.py
  lemarche/siaes/factories.py
  lemarche/siaes/management/commands/create_siae_activities.py
  lemarche/siaes/management/commands/sync_with_emplois_inclusion.py
  lemarche/siaes/migrations/0083_remove_historicalsiae_geo_range_and_more.py
  lemarche/siaes/migrations/0084_remove_historicalsiae_presta_type_and_more.py
  lemarche/siaes/models.py
  lemarche/siaes/tests/test_commands.py
  lemarche/siaes/tests/test_models.py
  lemarche/templates/dashboard/siae_edit_search.html
  lemarche/templates/siaes/_download_click_survey_modal_content.html
  lemarche/templates/siaes/_useful_infos.html
  lemarche/tenders/tests/test_matching.py
  lemarche/utils/apis/api_brevo.py
  lemarche/utils/templatetags/siae_sectors_display.py
  lemarche/utils/tests_templatetags.py
  lemarche/www/dashboard_siaes/forms.py
  lemarche/www/dashboard_siaes/views.py
  lemarche/www/siaes/forms.py
  lemarche/www/siaes/tests.py
  lemarche/www/siaes/views.py
  lemarche/www/tenders/tasks.py
Labels: enhancement

#1669 fix: bug sur les secteurs dans l'API des SIAE
  lemarche/api/siaes/serializers.py
  lemarche/api/siaes/views.py
  lemarche/siaes/models.py
Labels: bug

#1315 feat: Ajout d'un module django de guide pas à pas des utilisateurs
  config/settings/base.py
  config/urls.py
  lemarche/django_shepherd/__init__.py
  lemarche/django_shepherd/admin.py
  lemarche/django_shepherd/context_processor.py
  lemarche/django_shepherd/migrations/0001_initial.py
  lemarche/django_shepherd/migrations/__init__.py
  lemarche/django_shepherd/models.py
  lemarche/django_shepherd/static/django_shepherd/user_guide.js
  lemarche/django_shepherd/tests.py
  lemarche/django_shepherd/urls.py
  lemarche/django_shepherd/views.py
  lemarche/static/itou_marche/base/_custom.scss
  lemarche/static/itou_marche/base/_mixins.scss
  lemarche/static/itou_marche/base/_variables.scss
  lemarche/static/itou_marche/components/_autocomplete.scss
  lemarche/static/itou_marche/components/_collapse.scss
  lemarche/static/itou_marche/components/_forms.scss
  lemarche/static/itou_marche/components/_maparea.scss
  lemarche/static/itou_marche/components/_multiselect.scss
  lemarche/static/itou_marche/itou_marche.scss
  lemarche/static/itou_marche/layouts/_pages.scss
  lemarche/static/itou_marche/sections/_filiere.scss
  lemarche/static/itou_marche/sections/_home.scss
  lemarche/static/itou_marche/sections/_inclusion.scss
  lemarche/static/itou_marche/sections/_partenaires.scss
  lemarche/static/itou_marche/sections/_siae.scss
  lemarche/static/itou_marche/sections/_tender.scss
  lemarche/static/itou_marche/sections/_valoriser.scss
  lemarche/static/itou_marche/utils.scss
  lemarche/static/js/kind_multiselect_field.js
  lemarche/static/js/label_multiselect_field.js
  lemarche/static/js/legal_form_multiselect_field.js
  lemarche/static/js/network_multiselect_field.js
  lemarche/static/js/presta_type_multiselect_field.js
  lemarche/static/js/sector_multiselect_field.js
  lemarche/static/js/territory_multiselect_field.js
  lemarche/static/vendor/accessible-slick-1.0.1/slick.min.js
  lemarche/static/vendor/bootstrap-4.6.0/bootstrap.bundle.min.js
  lemarche/static/vendor/bootstrap-4.6.0/bootstrap.bundle.min.js.map
  lemarche/static/vendor/bootstrap-multiselect-1.1.1/bootstrap-multiselect.min.css
  lemarche/static/vendor/bootstrap-multiselect-1.1.1/bootstrap-multiselect.min.js
  lemarche/static/vendor/jquery-3.5.1/jquery-3.5.1.min.js
  lemarche/static/vendor/jquery-3.5.1/jquery-3.5.1.slim.min.js
  lemarche/static/vendor/shepherd-14.4.0/css/shepherd.css
  lemarche/static/vendor/shepherd-14.4.0/esm/shepherd.mjs
  lemarche/static/vendor/shepherd-14.4.0/esm/shepherd.mjs.map
  lemarche/templates/layouts/base.html
  lemarche/templates/siaes/search_results.html
  lemarche/utils/templatetags/theme_inclusion.py
  lemarche/www/dashboard_favorites/tests.py
  lemarche/www/siaes/tests.py
Labels: recette-jetable

#1662 feat: Menu déroulant "Mon espace" dans le header
  lemarche/static/itou_marche/components/_dropdown_menu.scss
  lemarche/static/itou_marche/itou_marche.scss
  lemarche/static/js/dropdown_menu.js
  lemarche/templates/dashboard/profile_edit.html
  lemarche/templates/favorites/dashboard_favorite_list_detail.html
  lemarche/templates/includes/_dropdown_menu.html
  lemarche/templates/layouts/_header_nav_primary_items.html
  lemarche/templates/layouts/base.html
  lemarche/templates/siaes/detail.html
  lemarche/templates/tenders/create_step_general.html
  lemarche/templates/tenders/siae_interested_list.html
  lemarche/www/auth/tests.py
  lemarche/www/tenders/tests.py
Labels: recette-jetable

#1670 fix: doubles imports alpineJs
  lemarche/templates/auth/signup.html
  lemarche/templates/cms/home_page.html
  lemarche/templates/dashboard/siae_edit_activities.html
  lemarche/templates/dashboard/siae_users.html
  lemarche/templates/pages/impact-calculator.html
  lemarche/templates/siaes/search_results.html
  lemarche/templates/tenders/create_step_detail.html
Labels: bug
